[bastion]
bastion_host ansible_host=98.92.94.75

[app_server]
app_server_host ansible_host=10.0.2.201

[all:vars]
ansible_user=ubuntu
# This is the SSH key you created in AWS
ansible_ssh_private_key_file=~/.ssh/webkeys.pem
